import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import UIProvider from "@/providers/UIProvider";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { ThemeProvider } from "@/providers/ThemeProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thiago Mecânico Oficina e Escola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.className} bg-gradient-to-t from-[#e9e9e9] to-[#fdfdfd] dark:from-[#444444] dark:to-tmDarkGray`}>
        <UIProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="relative overflow-hidden">{children}</main>
            <Footer />
          </ThemeProvider>
        </UIProvider>
      </body>
    </html>
  );
}
